version: '3'
services:
  web:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - 'rabbitmq'
      - 'postgres'
  rabbitmq:
    image: rabbitmq:alpine
  postgres:
    image: postgres:alpine
    env_file:
      - .env.local
    volumes:
      - ./pg_init.sql:/docker-entrypoint-initdb.d/pg_init.sql